app/urls.py
from django.urls import path
from app.views import (
  index,
  PostListView,
  post_detail,
  PostCreateView,
  post_edit,
  PostEditView,
  post_delete,
  PostDeleteView,
  UserProfileView,
  UserProfileRelationsView,
  UserProfileUpdateView,
  comment_create,
  CommentCreateView,
  CommentEditView,
  CommentDeleteView,
  accept_friend_request,
  AcceptFriendRequestView,
  reject_friend_request,
  cancel_friend_request,
  SendFriendRequestView,
  UnfriendView,
  RegisterView,
  LoginView,
  LogoutView,
)

urlpatterns = [
  path('', index, name='post_list'),
  path('', PostListView.as_view(), name='post_list'),
  path('register/', RegisterView.as_view(), name='register'),
  path('login/', LoginView.as_view(), name='login'),
  path('logout/', LogoutView.as_view(), name='logout'),
  path('post/<int:pk>', post_detail, name='post_detail'),
  path('post/create', PostCreateView.as_view(), name='post_create'),
  path('post/<int:pk>/edit', post_edit, name='post_edit'),
  path('post/<int:pk>/edit', PostEditView.as_view(), name='post_edit'),
  path('post/<int:pk>/delete', post_delete, name='post_delete'),
  path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
  path('post/<int:pk>/comment/create', comment_create, name='comment_create'),
  path('post/<int:pk>/comment/create', CommentCreateView.as_view(), name='comment_create'),
  path('post/<int:pk>/comment/<int:pk_comment>/edit', CommentEditView.as_view(), name='comment_edit'),
  path('post/<int:pk>/comment/<int:pk_comment>/delete', CommentDeleteView.as_view(), name='comment_delete'),
  path('userprofile/<int:pk>', UserProfileView.as_view(), name='user_profile'),
  path('userprofile/<int:pk>/relations', UserProfileRelationsView.as_view(), name='user_profile_relations'),
  path('userprofile/<int:pk>/edit', UserProfileUpdateView.as_view(), name='user_profile_edit'),
  # friends management
  # path('accept_friend_request/<int:user_pk>', accept_friend_request, name='accept_friend_request'),
  path('accept_friend_request/<int:user_pk>', AcceptFriendRequestView.as_view(), name='accept_friend_request'),
  path('reject_friend_request/<int:user_pk>', reject_friend_request, name='reject_friend_request'),
  path('cancel_friend_request/<int:user_pk>', cancel_friend_request, name='cancel_friend_request'),
  path('unfriend/<int:friend_pk>', UnfriendView.as_view(), name='unfriend'),
  path('send_friend_request/<int:user_pk>', SendFriendRequestView.as_view(), name='send_friend_request'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

app/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.CharField(max_length=200)
    image = models.FileField(upload_to='uploads/', blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE,related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} created by {} at {}".format(self.text, self.created_by.username, self.created_at)


class Country(models.Model):
    code = models.CharField(max_length=3, primary_key=True)
    name = models.CharField(max_length=70)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Countries"


class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='profile')
    birthday = models.DateField(blank=True, null=True)
    avatar = models.FileField(upload_to='media/', blank=True, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name="profiles", blank=True, null=True)
    friend_requests = models.ManyToManyField(User, related_name='friend_requests', blank=True)
    friends = models.ManyToManyField(User, related_name='friends', blank=True)


class Comment(models.Model):
    text = models.CharField(max_length=200)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} created by {} at {}".format(self.text, self.created_by.username, self.created_at)

app/forms.py
from django import forms
from app import models


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['text']


class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['text', 'image']


class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    e_mail = forms.CharField(max_length=100)
    class Meta:
        model = models.UserProfile
        exclude = ['user', 'friend_requests', 'friends']

app/templates/base.html
{% load static %}
<html>
  <head>
    <title>
      {% block title %}
      {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>

  </head>
  <body>
    {% include 'nav.html' %}

    {% block content %}
    {% endblock %}
  </body>
    {% block js %}
    {% endblock %}
</html>

app/templates/comment_delete.html
{% extends 'base.html' %}
{% block title %}
  Delete comment
{% endblock%}

{% block content %}
<div class="container m-5">
  <h5>Are you sure you want to delete this comment?</h5>
  <form method="post" class="form-inline">
    {% csrf_token %}
    <input class="btn btn-secondary" type="submit" value="Delete comment" />
  </form>
</div>
{% endblock %}

app/templates/comment_update.html
{% extends 'base.html' %}
{% block title %}
  Edit comment
{% endblock%}

{% block content %}
  <form method="post" class="form-inline justify-content-center">
    {% csrf_token %}
    <div class="form-group mx-2">
      <textarea rows="4" cols="50" class="form-control" type="text-area" 
      name="text" required="" id="id_text" maxlength="200">{{ form.text.initial }}</textarea>
    </div>
    <input class="btn btn-secondary" type="submit" value="Update comment"/>
  </form>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %} Social App {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <a class="btn btn-secondary" style="margin-left:1.2%;margin-top:5%;" href="{% url 'post_create' %}">
      Create post
    </a>
  {% endif %}

  <div class="row container">
    {% for post in post_list %}
      <div class="col-sm-6 p-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ post.text }}</h5>
            <p class="card-text">Created by: <a href="{% url 'user_profile' post.created_by.id %}">{{ post.created_by.username }}</a></p>
            <a href="{% url 'post_detail' post.id %}" class="btn btn-primary">See post details</a>
          </div>
          <div class="card-footer text-muted">
            {{ post.created_at }}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post" class="col-6">
    {% csrf_token %}
    <div class="form-group">
        {{ form.errors }}
    </div>

    <div class="form-group">
      <label for="id_username">Username:</label>
      <input type="text" name="username" class="form-control" autofocus="" required="" id="id_username" maxlength="150">
    </div>

    <div class="form-group">
      <label for="id_password">Password:</label>
      <input type="password" name="password" class="form-control" required="" id="id_password">
    </div>

    <button class="btn btn-primary" type="submit">Login</button>
  </form>
{% endblock %}

app/templates/nav.html
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'post_list' %}">Blog App</a>
  </li>

  {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'user_profile' user.id %}">Hello, {{ user.username }}</a>
    </li>
    {% if user.is_superuser %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'admin:index' %}">Admin</a>
    </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
    </li>
  {% else %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'login' %}">Login</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'register' %}">Register</a>
    </li>

  {% endif %}
  </ul>

app/templates/post_create.html
{% extends 'base.html' %}
{% block title %}
  Create post
{% endblock%}

{% block content %}
  <form method="post" class="form-inline justify-content-center" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group mx-2">
      <textarea rows="4" cols="50" class="form-control" type="text-area"
      name="text" required="" id="id_text" maxlength="200"></textarea>
    </div>
    <div class="form-group mx-2">
      <input type="file" name="image" id="id_image">
    </div>
    <input class="btn btn-secondary" type="submit" value="Create post" />
  </form>
{% endblock %}

app/templates/post_delete.html
{% extends 'base.html' %}

{% block title %}
  Delete post
{% endblock%}

{% block content %}
  <div class="container m-5">
    <h5>Are you sure you want to delete the post?</h5>
    <form method="post" class="form-inline">
        {% csrf_token %}
        <input class="btn btn-secondary" type="submit" value="Delete post" />
    </form>
  </div>
{% endblock %}

app/templates/post_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ post.text }}
{% endblock%}

{% block content %}
  <div class="container">
    <div class="p-3">
      <div class="card">
        {% if post.image %}
        <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
        {% endif %}
        <div class="card-body">
          <h1 class="card-title">
            {{ post.text }}
            {% if post.created_at|date:"Y-m-d H:i" != post.updated_at|date:"Y-m-d H:i" %}
              <small><i>(edited)</i></small>
            {% endif %}
          </h1>
          <p class="card-text">Created by:
            <a href="{% url 'user_profile' post.created_by.id %}">{{ post.created_by.username }}</a>
          </p>
        </div>
        <div class="card-footer text-muted">
          {{ post.created_at }}
        </div>
      </div>
    </div>

    <div class="m-2">
      {% if user == post.created_by %}
        <a class="btn btn-secondary" href="{% url 'post_edit' post.id %}">Edit post</a>
        <a class="btn btn-secondary" href="{% url 'post_delete' post.id %}">Delete post</a>
      {% endif %}
    </div>

    <div class=" col-sm-12">
      <h2>Comments</h2>

      {% if user.is_authenticated %}
        <form action="{% url 'comment_create' post.id %}" method="post" class="form-inline justify-content-center">
          {% csrf_token %}
          <!--{{ form.as_p }}-->
          <div class="form-group mx-2">
            <input class="form-control" type="text" name="text" required="" id="id_text" maxlength="200">
          </div>
          <input class="btn btn-secondary" type="submit" value="Comment" />
        </form>
      {% endif %}

      {% if post.comments.all %}
        {% regroup post.comments.all|dictsortreversed:"created_at" by created_at as comments %}
        {% for comment_group in comments %}
          {% for comment in comment_group.list %}
          <div class="card m-3">
            {% if user == comment.created_by %}
              <div class="m-2">
                <a class="btn btn-secondary" href="{% url 'comment_edit' post.id comment.id %}">Edit comment</a>
                <a class="btn btn-secondary" href="{% url 'comment_delete' post.id comment.id %}">Delete comment</a>
              </div>
            {% endif %}
            <div class="card-body">
              <blockquote class="blockquote mb-0">
                <p>
                  {{ comment.text }}
                  {% if comment.created_at|date:"Y-m-d H:i" !=  comment.updated_at|date:"Y-m-d H:i" %}
                    <small><i>(edited)</i></small>
                  {% endif %}
                </p>
                <footer class="blockquote-footer">commented by
                  <cite><a href="{% url 'user_profile' comment.created_by.id %}">{{ comment.created_by.username }}</a></cite>
                  on <cite>{{ comment.created_at }}</cite>
                </footer>
              </blockquote>
            </div>
          </div>
          {% endfor%}
        {% endfor %}
      {% else %}
        <p> No comments yet.</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

app/templates/post_update.html
{% extends 'base.html' %}
{% block title %}
  Edit post
{% endblock%}

{% block content %}
  <form method="post" class="form-inline justify-content-center">
    {% csrf_token %}
    <div class="form-group mx-2">
      <textarea rows="4" cols="50" class="form-control" type="text-area" 
      name="text" required="" id="id_text" maxlength="200">{{ form.text.initial }}</textarea>
    </div>
    <input class="btn btn-secondary" type="submit" value="Update post" />
  </form>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post" class="col-6">
    {% csrf_token %}
    <div class="form-group">
        {{ form.errors }}
    </div>

    <div class="form-group">
      <label for="id_username">Username:</label>
      <input type="text" name="username" class="form-control" autofocus="" required="" id="id_username" maxlength="150">
    </div>

    <div class="form-group">
      <label for="id_password1">Password:</label>
      <input type="password" name="password1" class="form-control" required="" id="id_password1">
    </div>

    <div class="form-group">
      <label for="id_password2">Password confirmation:</label>
      <input type="password" name="password2" class="form-control" required="" id="id_password2">
    </div>

    <button class="btn btn-primary" type="submit">Register</button>
  </form>
{% endblock %}

app/templates/user_profile.html
{% extends 'base.html' %}

{% block title %} User Profile - {{ userprofile.user.username }} {% endblock %}

{% block content %}
  <div class="container">
    {% if user == userprofile.user %}
      <div class="m-2">
        <a class="btn btn-primary" href="{% url 'user_profile_edit' userprofile.id %}">Edit profile</a>
        <a class="btn btn-primary" href="{% url 'user_profile_relations' userprofile.user.id %}">See your relations</a>
      </div>
    {% endif %}

    {% if user != userprofile.user %}
      {% if user in userprofile.friend_requests.all %}
        <a class="btn btn-secondary" href="{% url 'accept_friend_request' userprofile.user.id %}">Accept friend request</a>
        <a class="btn btn-secondary" href="{% url 'reject_friend_request' userprofile.user.id %}">Reject friend request</a>
      {% else %}
        {% if user not in userprofile.friends.all %}
          {% if userprofile.user not in user.profile.first.friend_requests.all %}
            <a class="btn btn-secondary" href="{% url 'send_friend_request' userprofile.user.id %}">Send friend request</a>
          {% else %}
            <a class="btn btn-secondary" href="{% url 'cancel_friend_request' userprofile.user.id %}">Cancel friend request</a>
          {% endif %}
        {% else %}
          <a class="btn btn-secondary" href="{% url 'unfriend' userprofile.user.id %}">Unfriend</a>
        {% endif %}
      {% endif %}
    {% endif %}

    <h1>{{ userprofile.user.username }}' Profile</h1>
    {% if user in userprofile.friends.all or user == userprofile.user %}
    <ul class="list-group m-4">
      {% if userprofile.avatar %}
      <p><b>Avatar:</b></p><img style="margin-bottom:20px;" src="{{ userprofile.avatar.url }}" width="200px">
      {% endif %}
      <li class="list-group-item"><b>Fullname:</b> {{ userprofile.user.first_name }} {{ userprofile.user.last_name }}</li>
      <li class="list-group-item"><b>Username:</b> {{ userprofile.user.username }}</li>
      <li class="list-group-item"><b>E-mail:</b> {{ userprofile.user.email }}</li>
      <li class="list-group-item"><b>Birthday:</b> {{ userprofile.birthday }}</li>
      <li class="list-group-item"><b>Country:</b> {{ userprofile.country.name }}</li>
    </ul>
    {% endif %}
  </div>
{% endblock %}

app/templates/user_profile_relations.html
{% extends 'base.html' %}

{% block title %} {{ userprofile.user.username }}'s relations {% endblock %}

{% block content %}
<div class="container">
<h3>Your relations</h1>

<h4>Friends:
  {% for friend in userprofile.friends.all %}
    <span><a href="{% url 'user_profile' friend.id %}">{{ friend.username }}</a></span>
  {% empty %}
    <span>No friends</span>
  {% endfor %}
</h4>

<h4>Friends you requested :
    {% for friend_request in userprofile.friend_requests.all %}
      <span><a href="{% url 'user_profile' friend_request.id %}">{{ friend_request.username }}</a></span>
    {% empty %}
      <span>No requests</span>
    {% endfor %}
</h4>

<h4>People that requested your friendship:
    {% for friend_request in userprofile.user.friend_requests.all %}
      <span><a href="{% url 'user_profile' friend_request.user.id %}">{{ friend_request.user.username }}</a></span>
    {% empty %}
      <span>No requests</span>
    {% endfor %}
  </h4>
{% endblock %}

app/templates/user_profile_update.html
{% extends 'base.html' %}
{% block title %}
  Edit profile
{% endblock%}

{% block content %}
  <form method="post" class="justify-content-center col-6" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form.errors }}
    <div class="form-group mx-2">
      <label for="id_birthday">Birthday:</label>
      <input type="text" name="birthday" value="{{ form.birthday.initial | date:'Y-m-d' }}"
             id="id_birthday">
    </div>

    <div class="form-group mx-2">
      <label for="id_country">Country:</label> 
      <select name="country" class="form-control" id="id_country">
        {% for value, key in form.fields.country.choices %}
          <option value="{{ value }}"{% if form.initial.country == value %} selected {% endif %}>
            {{ key }}
          </option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group mx-2">
      <label for="id_first_name">First name:</label>
      <input type="text" class="form-control" name="first_name" 
             value="{{ form.first_name.initial }}" required="" id="id_first_name" 
             maxlength="100">
    </div>

    <div class="form-group mx-2">
      <label for="id_last_name">Last name:</label>
      <input type="text" class="form-control" name="last_name" 
             required="" id="id_last_name" maxlength="100" 
             value="{{ form.last_name.initial }}">
    </div>

    <div class="form-group mx-2">
      <label for="id_e_mail">E-mail:</label>
      <input type="text"  class="form-control" name="e_mail" 
             required="" id="id_e_mail" maxlength="100"
             value="{{ form.e_mail.initial }}">
    </div>

    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text" id="inputGroupFileAddon01">Avatar upload</span>
      </div>
      <div class="custom-file">
        <input type="file" name="avatar" id="id_avatar" class="custom-file-input">
        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
      </div>
    </div>
    <input style="margin-top:20px;" class="btn btn-secondary" type="submit" value="Update profile" />
  </form>
{% endblock %}

{% block js %}
<script>
  $(".custom-file-input").on("change", function() {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
  });
</script>
{% endblock %}